### ISSUE TITLE
Json报错

### ISSUE THREAD

**Issue by luzonghaoa** [YaboSu/zhihu_crawler#2]
D:\Files>python paqu.py
Traceback (most recent call last):
  File "paqu.py", line 4, in <module>
    session = zh_crawler.get_login_session()
  File "D:\Files\zhihu_crawler\zh_crawler.py", line 21, in get_login_session
    login_result = session.post('http://www.zhihu.com/login/email', data=config, headers=defalut_headers).json()
  File "C:\Users\lwz\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\lwz\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lwz\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lwz\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

json文件我也就把<>內填上了username和password，不知道为什么会报错啊

**Comment by YaboSu** [comment]
知乎的登录验证方式变了，是请求的返回内容的报错。
